name: Run Action Class

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Compile Action class
      run: javac /Action.java

    - name: Run Action class
      run: java -cp /Action
